name: Nightly Release

on:
  schedule:
    - cron:  '25 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Vars
        id: set-vars
        env:
          GITHUB_TOKEN: ${{ secrets.NIGHTLY_BUILD_GH_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        run: |
          echo "LATEST_STABLE_TAG=$(gh release list -R ${{ github.repository}} | grep -v nightly | awk '{ print $1}' | head -1)"  >> $GITHUB_ENV
          echo "Latest Stable Tag: $LATEST_STABLE_TAG"
          echo "NIGHTLY_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
          echo "Creating for Nightly: $NIGHTLY_DATE"
      - name: Create Release
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.NIGHTLY_BUILD_GH_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        run: |
          gh release create  nightly-${NIGHTLY-DATE} -R ${{github.repository}}  --notes "MapTool Nightly Build for ${NIGHTLY_DATE}" --generate-notes -p -target develop